import type { SongKey } from "@/shared/song/songKeyOptions";
import type { ChordDisplayModeType } from "@/shared/user/chord-display/effectiveChordDisplayMode";

const displayedRootByMode: Readonly<
	Record<Exclude<ChordDisplayModeType, "roman">, Readonly<Record<SongKey, string>>>
> = {
	german: {
		"A": "A",
		"A#": "A♯",
		"Ab": "A♭",
		"B": "H",
		"Bb": "B",
		"C": "C",
		"C#": "C♯",
		"D": "D",
		"D#": "D♯",
		"Db": "D♭",
		"E": "E",
		"Eb": "E♭",
		"F": "F",
		"F#": "F♯",
		"G": "G",
		"G#": "G♯",
		"Gb": "G♭",
	},
	letters: {
		"A": "A",
		"A#": "A♯",
		"Ab": "A♭",
		"B": "B",
		"Bb": "B♭",
		"C": "C",
		"C#": "C♯",
		"D": "D",
		"D#": "D♯",
		"Db": "D♭",
		"E": "E",
		"Eb": "E♭",
		"F": "F",
		"F#": "F♯",
		"G": "G",
		"G#": "G♯",
		"Gb": "G♭",
	},
	sargam: {
		"A": "D",
		"A#": "D♯",
		"Ab": "D♭",
		"B": "N",
		"Bb": "N♭",
		"C": "S",
		"C#": "S♯",
		"D": "R",
		"D#": "R♯",
		"Db": "R♭",
		"E": "G",
		"Eb": "G♭",
		"F": "M",
		"F#": "M♯",
		"G": "P",
		"G#": "P♯",
		"Gb": "P♭",
	},
	solfege: {
		"A": "La",
		"A#": "La♯",
		"Ab": "La♭",
		"B": "Si",
		"Bb": "Si♭",
		"C": "Do",
		"C#": "Do♯",
		"D": "Ré",
		"D#": "Ré♯",
		"Db": "Ré♭",
		"E": "Mi",
		"Eb": "Mi♭",
		"F": "Fa",
		"F#": "Fa♯",
		"G": "Sol",
		"G#": "Sol♯",
		"Gb": "Sol♭",
	},
} as const;

export default displayedRootByMode;
