import { describe, expect, it } from "bun:test";

import { buildDevVarsContent, parseWorkerVarNames } from "./generate-dev-vars";

describe("generate-dev-vars", () => {
	it("parses worker var names", () => {
		expect(parseWorkerVarNames("A\n# comment\nB\n")).toStrictEqual(["A", "B"]);
	});

	it("builds dev vars content from provided values", () => {
		expect(buildDevVarsContent(["ALPHA", "BETA"], { ALPHA: "1", BETA: "" })).toBe(
			"# Auto-generated by scripts/env/generate-dev-vars.bun.ts - do not edit manually.\n" +
				"# Regenerate with: bun run scripts/env/generate-dev-vars.bun.ts\n" +
				"\n" +
				"ALPHA=1\n",
		);
	});
});
