import { parseListLines } from "./env-utils";

const MIN_LINE_LENGTH = 1;

export function buildDevVarsContent(varNames: readonly string[], values: Readonly<Record<string, string>>): string {
	const lines = [
		"# Auto-generated by scripts/env/generate-dev-vars.bun.ts - do not edit manually.",
		"# Regenerate with: bun run scripts/env/generate-dev-vars.bun.ts",
		"",
	];

	for (const varName of varNames) {
		const value = values[varName];
		if (typeof value === "string" && value !== "") {
			lines.push(`${varName}=${value}`);
		}
	}

	return `${lines.join("\n")}\n`;
}

export function parseWorkerVarNames(text: string): string[] {
	return parseListLines(text, MIN_LINE_LENGTH);
}
