import { describe, expect, it } from "bun:test";

import buildDevVarsContent from "./buildDevVarsContent";

const VAR_A = "DB_HOST";
const VAR_B = "APP_SECRET";
const VAR_C = "PORT";
const VAL_A = "localhost";
const VAL_B = "s3cr3t";
const VAL_C = "3000";

const HEADER = `# Auto-generated by scripts/env/generate-dev-vars/generate-dev-vars.bun.ts - do not edit manually.\n# Regenerate with: bun run scripts/env/generate-dev-vars/generate-dev-vars.bun.ts\n\n`;

describe("buildDevVarsContent", () => {
	const cases: {
		name: string;
		varNames: string[];
		values: Record<string, string>;
		expected: string;
	}[] = [
		{
			name: "empty varNames produces only the header",
			varNames: [],
			values: {},
			expected: HEADER,
		},
		{
			name: "vars with empty string values are omitted",
			varNames: [VAR_A, VAR_B],
			values: { [VAR_A]: "", [VAR_B]: "" },
			expected: HEADER,
		},
		{
			name: "var absent from values map is omitted",
			varNames: [VAR_A],
			values: {},
			expected: HEADER,
		},
		{
			name: "single var with a value is included after the header",
			varNames: [VAR_A],
			values: { [VAR_A]: VAL_A },
			expected: `${HEADER}${VAR_A}=${VAL_A}\n`,
		},
		{
			name: "multiple vars with values are all included in order",
			varNames: [VAR_A, VAR_B, VAR_C],
			values: { [VAR_A]: VAL_A, [VAR_B]: VAL_B, [VAR_C]: VAL_C },
			expected: `${HEADER}${VAR_A}=${VAL_A}\n${VAR_B}=${VAL_B}\n${VAR_C}=${VAL_C}\n`,
		},
		{
			name: "varNames order is preserved in the output",
			varNames: [VAR_C, VAR_A, VAR_B],
			values: { [VAR_A]: VAL_A, [VAR_B]: VAL_B, [VAR_C]: VAL_C },
			expected: `${HEADER}${VAR_C}=${VAL_C}\n${VAR_A}=${VAL_A}\n${VAR_B}=${VAL_B}\n`,
		},
		{
			name: "mix of present and missing vars includes only present ones",
			varNames: [VAR_A, VAR_B, VAR_C],
			values: { [VAR_A]: VAL_A, [VAR_C]: VAL_C },
			expected: `${HEADER}${VAR_A}=${VAL_A}\n${VAR_C}=${VAL_C}\n`,
		},
		{
			name: "extra keys in values map that are not in varNames are ignored",
			varNames: [VAR_A],
			values: { [VAR_A]: VAL_A, [VAR_B]: VAL_B },
			expected: `${HEADER}${VAR_A}=${VAL_A}\n`,
		},
	];

	it.each(cases)("$name", ({ varNames, values, expected }) => {
		// Act
		const result = buildDevVarsContent(varNames, values);

		// Assert
		expect(result).toBe(expected);
	});
});
