/**
 * Builds the content of the `.dev.vars` file from a list of variable names and their values.
 *
 * Variables with empty or missing values are omitted. The output includes a
 * header comment warning against manual edits.
 *
 * @param varNames - Ordered list of variable names to include.
 * @param values - Map of variable name to value; entries with empty strings are skipped.
 * @returns The formatted `.dev.vars` file content, terminated with a newline.
 */
export default function buildDevVarsContent(
	varNames: readonly string[],
	values: Readonly<Record<string, string>>,
): string {
	const lines = [
		"# Auto-generated by scripts/env/generate-dev-vars/generate-dev-vars.bun.ts - do not edit manually.",
		"# Regenerate with: bun run scripts/env/generate-dev-vars/generate-dev-vars.bun.ts",
		"",
	];

	for (const varName of varNames) {
		const value = values[varName];
		if (typeof value === "string" && value !== "") {
			lines.push(`${varName}=${value}`);
		}
	}

	return `${lines.join("\n")}\n`;
}
